export function assertExhaustive(x) {
    throw new Error("Unexpected object: " + x);
}
export async function tryCatch(promise) {
    if (!promise) {
        return [null, undefined];
    }
    try {
        const data = await promise;
        return [null, data];
    }
    catch (error) {
        return [error, null];
    }
}
export function promiseWithResolvers() {
    let resolve;
    let reject;
    const promise = new Promise((_resolve, _reject) => {
        resolve = _resolve;
        reject = _reject;
    });
    return {
        promise,
        resolve,
        reject,
    };
}
//# sourceMappingURL=utils.js.map